- model: llava
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/runs/robustlmm/metaclip/finetune/ptn_ft0_new/llava_v1_5
  tasks: seedbench_2,seedbench_2_plus
  batch_size: 1
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval,job_type=eval,name=seedbench_2_llavaallp0a1
  log_samples_suffix: seedbench_2
  output_path: "./logs/robustlmm/final_reses/llava_res/llava_balance"