- model: llava
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/model/mm/ckpts/sft_palo/llava_checkpoint_1000,peft_model_path=/mnt/petrelfs/songmingyang/songmingyang/model/mm/ckpts/topk/5.5k/top3
  batch_size: 1
  tasks: pope_mul_coco_a_r,pope_mul_aokvqa_a_r,pope_mul_gqa_a_r
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval,job_type=eval,name=top3_supply
  log_samples_suffix: top3_supply
  output_path: "./logs/"

