- model: sharegpt4v
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/model/mm/ShareGPT4V-7B,model_name=sharegpt4v
  tasks: pope,mme,vqav2,gqa,vizwiz_vqa,scienceqa_full,seedbench,seedbench-2,refcoco,refcoco+,mmmu,textvqa,ok_vqa,flickr30k
  batch_size: 1
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval,job_type=eval,name=share4v_baseline
  log_samples_suffix: share4v_baseline
  output_path: "./logs/robustlmm/sharegpt4v"
