- model: llava
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/model/mm/ckpts/sft_palo/llava_checkpoint_1000
  tasks: mme_mul
  batch_size: 1
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval-mme,job_type=eval,name=llava_s1000
  log_samples_suffix: mme_llava_s1000
  output_path: "./logs/"

