- model: llava
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/model/others/llava-v1.5-7b
  tasks: mme_mul
  batch_size: 1
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval-mme,job_type=eval,name=llava_baseline
  log_samples_suffix: mme_llava_baseline
  output_path: "./logs/"

