- model: llava
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/model/mm/ckpts/sft_palo/llava_checkpoint_1000,peft_model_path=/mnt/petrelfs/songmingyang/songmingyang/runs/llava/dpo/checkpoints/palo_sfted_self_hallu_human
  tasks: pope_gqa_mul
  batch_size: 1
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval,job_type=eval,name=gqa_s1000_sh_hpfinal
  log_samples_suffix: eval_pope_gqa_mul_s1000_sh_hpfinal
  output_path: "./logs/"

