- model: llava
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/model/others/llava-v1.5-7b
  tasks: pope_aokvqa_mul
  batch_size: 1
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval,job_type=eval,name=aokvqa_baseline
  log_samples_suffix: eval_pope_aokvqa_mul_baseline
  output_path: "./logs/"

