- model: sharegpt4v
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/runs/robustlmm/metaclip/sharegpt4v/ft/pttoca1diff_ftalla09_diff_tocw,model_name=sharegpt4v
  tasks: pope,mme,vqav2,gqa,vizwiz_vqa,scienceqa_full,seedbench,seedbench-2,refcoco,refcoco+,mmmu,textvqa,ok_vqa,flickr30k
  batch_size: 1
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval,job_type=eval,name=pttocp0a1diff_ftalla09diff
  log_samples_suffix: pttocp0a1diff_ftalla09diff
  output_path: "./logs/robustlmm/sharegpt4v/pttocp0a1diff_ftalla09diff"
