- model: llava
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/model/mm/ckpts/sft_palo/llava_checkpoint_1000,peft_model_path=/mnt/petrelfs/songmingyang/songmingyang/model/mm/ckpts/supply_high_low_1_2/5.5k
  batch_size: 1
  tasks: pope_mul,pope_aokvqa_mul,pope_gqa_mul,mme_mul
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval,job_type=eval,name=high_low_1_2_5_5k
  log_samples_suffix: high_low_1_2_5_5k
  output_path: "./logs/"

