- model: llava
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/runs/robustlmm/metaclip/finetune/comp_token_co_occurrence_what_word/llava_v1_5
  tasks: pope,mme,vqav2,gqa,vizwiz_vqa,scienceqa_full,seedbench,seedbench-2,refcoco,refcoco+,mmmu,textvqa,ok_vqa,flickr30k
  batch_size: 1
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval,job_type=eval,name=eval_all_meta_clip_comp_token_co_occurrence_what_word
  log_samples_suffix: eval_all_meta_clip_comp_token_co_occurrence_what_word
  output_path: "./logs/robustlmm/meta_clip"
