dataset_kwargs:
  data_files:
    test:
    - /mnt/petrelfs/songmingyang/songmingyang/data/mm/annotation/pope_mul_reconstructed/gqa/sv/gqa_pope_adversarial_sv.json
    - /mnt/petrelfs/songmingyang/songmingyang/data/mm/annotation/pope_mul_reconstructed/gqa/sv/gqa_pope_random_sv.json
  token: true
dataset_path: json
doc_to_target: label
doc_to_text: !function 'utils.pope_doc_to_text'
doc_to_visual: !function 'utils.pope_doc_to_visual'
generation_kwargs:
  do_sample: false
  max_new_tokens: 128
  num_beams: 1
  temperature: 0
  top_p: 0
group: pope_mul_gqa_a_r
metadata:
- version: 0.0
metric_list:
- aggregation: !function 'utils.pope_aggregate_accuracy'
  higher_is_better: true
  metric: pope_random_accuracy
- aggregation: !function 'utils.pope_aggregate_accuracy'
  higher_is_better: true
  metric: pope_adversarial_accuracy
- aggregation: !function 'utils.pope_aggregate_precision'
  higher_is_better: true
  metric: pope_random_precision
- aggregation: !function 'utils.pope_aggregate_precision'
  higher_is_better: true
  metric: pope_adversarial_precision
- aggregation: !function 'utils.pope_aggregate_recall'
  higher_is_better: true
  metric: pope_random_recall
- aggregation: !function 'utils.pope_aggregate_recall'
  higher_is_better: true
  metric: pope_adversarial_recall
- aggregation: !function 'utils.pope_aggregate_f1_score'
  higher_is_better: true
  metric: pope_random_f1_score
- aggregation: !function 'utils.pope_aggregate_f1_score'
  higher_is_better: true
  metric: pope_adversarial_f1_score
- aggregation: !function 'utils.pope_aggregate_yes_ratio'
  higher_is_better: true
  metric: pope_random_yes_ratio
- aggregation: !function 'utils.pope_aggregate_yes_ratio'
  higher_is_better: true
  metric: pope_adversarial_yes_ratio
output_type: generate_until
process_results: !function 'utils.pope_process_results'
task: pope_mul_gqa_a_r_sv
test_split: test
