group: pope_mul_10lang
metadata:
  version: 0.0
task:
- pope_mul_en
- pope_mul_ru
- pope_mul_de
- pope_mul_zh
- pope_mul_ja
- pope_mul_fr
- pope_mul_es
- pope_mul_pt 
- pope_mul_uk
- pope_mul_bg 
- pope_mul_tr
- pope_mul_ar
- pope_mul_ko
- pope_mul_coco_a_r_en
- pope_mul_coco_a_r_ru
- pope_mul_coco_a_r_de
- pope_mul_coco_a_r_zh
- pope_mul_coco_a_r_ja
- pope_mul_coco_a_r_fr
- pope_mul_coco_a_r_es
- pope_mul_coco_a_r_pt 
- pope_mul_coco_a_r_uk
- pope_mul_coco_a_r_bg 
- pope_mul_coco_a_r_tr
- pope_mul_coco_a_r_ar
- pope_mul_coco_a_r_ko
- pope_aokvqa_mul_en
- pope_aokvqa_mul_ru
- pope_aokvqa_mul_de
- pope_aokvqa_mul_zh
- pope_aokvqa_mul_ja
- pope_aokvqa_mul_fr
- pope_aokvqa_mul_es
- pope_aokvqa_mul_pt 
- pope_aokvqa_mul_uk
- pope_aokvqa_mul_bg 
- pope_aokvqa_mul_tr
- pope_aokvqa_mul_ar
- pope_aokvqa_mul_ko
- pope_mul_aokvqa_a_r_en
- pope_mul_aokvqa_a_r_ru
- pope_mul_aokvqa_a_r_de
- pope_mul_aokvqa_a_r_zh
- pope_mul_aokvqa_a_r_ja
- pope_mul_aokvqa_a_r_fr
- pope_mul_aokvqa_a_r_es
- pope_mul_aokvqa_a_r_pt 
- pope_mul_aokvqa_a_r_uk
- pope_mul_aokvqa_a_r_bg 
- pope_mul_aokvqa_a_r_tr
- pope_mul_aokvqa_a_r_ar
- pope_mul_aokvqa_a_r_ko
- pope_gqa_mul_en
- pope_gqa_mul_ru
- pope_gqa_mul_de
- pope_gqa_mul_zh
- pope_gqa_mul_ja
- pope_gqa_mul_fr
- pope_gqa_mul_es
- pope_gqa_mul_pt 
- pope_gqa_mul_uk
- pope_gqa_mul_bg 
- pope_gqa_mul_tr
- pope_gqa_mul_ar
- pope_gqa_mul_ko
- pope_mul_gqa_a_r_en
- pope_mul_gqa_a_r_ru
- pope_mul_gqa_a_r_de
- pope_mul_gqa_a_r_zh
- pope_mul_gqa_a_r_ja
- pope_mul_gqa_a_r_fr
- pope_mul_gqa_a_r_es
- pope_mul_gqa_a_r_pt 
- pope_mul_gqa_a_r_uk
- pope_mul_gqa_a_r_bg 
- pope_mul_gqa_a_r_tr
- pope_mul_gqa_a_r_ar
- pope_mul_gqa_a_r_ko