- model: mblip
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/model/mm/mblip/mblip-mt0-xl
  tasks: pope_mul
  batch_size: 1
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval,job_type=eval,name=coco_mblip
  log_samples_suffix: pope_coco_mblip
  output_path: "./logs/"

