- model: llava
  model_args: pretrained=/mnt/petrelfs/songmingyang/songmingyang/model/mm/ckpts/sft_palo/llava_checkpoint_1000,peft_model_path=/mnt/petrelfs/songmingyang/songmingyang/model/mm/ckpts/topk/5.5k/top5
  batch_size: 1
  tasks: pope_mul,pope_aokvqa_mul,pope_gqa_mul,mme_mul
  log_samples: true
  wandb_log_samples: true
  wandb_args: project=lmms-eval,job_type=eval,name=top5_5.5k
  log_samples_suffix: top5_5.5k
  output_path: "./logs/"

